const artirstFollow = [
  {
    id: 1,
    image: './img/sontung.jpg',
    image1: './img/goeun.jpg',
    name: 'son tung mtp',
    songName: 'I will go to the first snow',
    follower: '1.000.000',
    song: '100',
    repeat: '1.267',
    heart: '50',
  },
  {
    id: 2,
    image: './img/sontung.jpg',
    image1: './img/goeun.jpg',
    name: 'son tung mtp',
    songName: 'I will go to the first snow',
    follower: '1.000.000',
    song: '100',
    repeat: '1.267',
    heart: '50',
  },
  {
    id: 3,
    image: './img/sontung.jpg',
    image1: './img/goeun.jpg',
    name: 'son tung mtp',
    songName: 'I will go to the first snow',
    follower: '1.000.000',
    song: '100',
    repeat: '1.267',
    heart: '50',
  },
];
export default artirstFollow;
